shua1/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ----------------------------------------------------------------------------------------------------------------------------------------------
// ----------------------------------------------------------------------------------------------------------------------------------------------

// იმისთვის რომ Route კლასზე გადაცემული კონტროლერების სახელებს სწორი namespace_ით მივაკითხოთ
// app/Providers/RouteServiceProvider.php ფაილში განაკომენტარეთ შემდეგი ხაზი: protected $namespace = 'App\\Http\\Controllers';

// ----------------------------------------------------------------------------------------------------------------------------------------------

Route::view('/welcome', 'welcome');     // return view

Route::redirect('/go', '/to');          // redirect route address '/go' to route address '/to'
Route::redirect('/to', '/home');        // redirect route address '/to' to route address '/home'

Route::get('/', function () {           // redirect route address '/' to route named 'home'
    return redirect('home'); 
    // return redirect()->route('home');
});

// ----------------------------------------------------------------------------------------------------------------------------------------------

Route::prefix('posts')->name('posts.')->group( function () {

    Route::get(     "",              'PostController@index'      )->name('index');        // მაჩვენე ყველა პოსტის გვედრი 

    Route::get(     "create",        'PostController@create'     )->name("create");       // მაჩვენე ახალი პოსტის შესაქმნელი გვერდი
    Route::post(    "",              'PostController@store'      )->name("store");        // შექმენი პოსტი

    Route::get(     "{post}",        'PostController@show'       )->name("show");         // მაჩვენე კონკრეტული პოსტის გვერდი

    Route::get(     "{post}/edit",   'PostController@edit'       )->name("edit");         // მაჩვენე კონკრეტული პოსტის შესაცვლელი გვერდი
    Route::put(     "{post}",        'PostController@update'     )->name("update");       // შეცვალე კონკრეტული პოსტი

    Route::delete(  "{post}",        'PostController@destroy'    )->name("destroy");      // წაშალე კონკრეტული პოსტი

    Route::post(    "ajax",          'PostController@indexAjax'  )->name("ajax");

});

// ----------------------------------------------------------------------------------------------------------------------------------------------

Route::middleware('auth')->group( function () {

    Route::get(     '/home',            'HomeController@index'          )->name('home');
    Route::get(     '/notifications',   'NotificationsController@show'  )->name('notifications.show');

});

// ----------------------------------------------------------------------------------------------------------------------------------------------

Route::get(     '/contact',         'ContactController@show'        )->name('contact.show');
Route::post(    '/contact',         'ContactController@store'       )->name('contact.store');

// ----------------------------------------------------------------------------------------------------------------------------------------------

Auth::routes();

// ----------------------------------------------------------------------------------------------------------------------------------------------

Route::fallback(function () { echo "გვერდი ვერ მოიძებნა"; });

shua1/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @include('layouts.authlinks')
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

shua1/resources/views/layouts/authlinks.blade.php
<!-- Authentication Links -->
@guest
    @if (Route::has('login'))
        <li class="nav-item">
            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>
    @endif

    @if (Route::has('register'))
        <li class="nav-item">
            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
        </li>
    @endif
@else
    <li class="nav-item dropdown">
        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
            {{ Auth::user()->name }}
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('logout') }}"
            onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                {{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </li>
@endguest

shua1/resources/views/layouts/flash-message.blade.php
<div class="alert alert-{{ $class }}">
    <button type="button" class="close" data-dismiss="alert">×</button>	
    <strong>{{ $message }}</strong>
</div>

shua1/resources/views/layouts/flash-messages.blade.php
@if ($message = Session::get('success'))
    @include('layouts.flash-message', [
        'class'     => 'success alert-block',
        'message'   => $message
    ])
@endif

@if ($message = Session::get('error'))
    @include('layouts.flash-message', [
        'class'     => 'danger alert-block',
        'message'   => $message
    ])
@endif

@if ($message = Session::get('warning'))
    @include('layouts.flash-message', [
        'class'     => 'warning alert-block',
        'message'   => $message
    ])
@endif

@if ($message = Session::get('info'))
    @include('layouts.flash-message', [
        'class'     => 'info alert-block',
        'message'   => $message
    ])
@endif

@if ($errors->any())
    @include('layouts.flash-message', [
        'class'     => 'danger',
        'message'   => 'Please check the form below for errors'
    ])
@endif

shua1/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>FREE RESPONSIVE HORIZONTAL ADMIN</title>
    <!-- BOOTSTRAP CORE STYLE  -->
    <link href="{{ asset('assets/css/bootstrap.css') }}" rel="stylesheet" />
    <!-- FONT AWESOME STYLE  -->
    <link href="{{ asset('assets/css/font-awesome.css') }}" rel="stylesheet" />
    <!-- CUSTOM STYLE  -->
    <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet" />
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet" />
    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <!-- jQuery CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

</head>

<body>
    <div class="navbar navbar-inverse set-radius-zero">
        <div class="container">

            <!-- Logo -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ route('home') }}">

                    <img src="{{ asset('assets/img/logo.png') }}" />
                </a>

            </div>

            <!-- Authentication Links -->
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar">
                        <ul id="menu-top" class="nav navbar-nav navbar-right">                            
                            
                            @auth 
                                <li><a href="{{ route('notifications.show') }}">NOTIFICATIONS</a></li>
                            @endauth

                            @include('layouts.authlinks')

                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
    
    <!-- LOGO HEADER END-->
    <section class="menu-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-collapse collapse ">
                        <ul id="menu-top" class="nav navbar-nav navbar-right">
                            
                            <li><a href="{{ route('home') }}">HOME</a></li>

                            <li><a href="{{ route('posts.index') }}">POSTS</a></li>

                            <li><a href="{{ route('contact.show') }}">CONTACT</a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- MENU SECTION END-->
    <div class="content-wrapper">
        <div class="container">


            @include('layouts.flash-messages')
            
            @yield('content')


        </div>
    </div>
    <!-- CONTENT-WRAPPER SECTION END-->
    <section class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    &copy; 2014 Yourdomain.com |<a href="http://www.binarytheme.com/" target="_blank"> Designed by :
                        binarytheme.com</a>
                </div>

            </div>
        </div>
    </section>
    <!-- FOOTER SECTION END-->
    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY  -->
    <script src="{{ asset('assets/js/jquery-1.10.2.js') }}"></script>
    <!-- BOOTSTRAP SCRIPTS  -->
    <script src="{{ asset('assets/js/bootstrap.js') }}"></script>
    <!-- CUSTOM SCRIPTS  -->
    <script src="{{ asset('assets/js/custom.js') }}"></script>
</body>

</html>

shua1/resources/views/layouts/post.blade.php
<div class="col-md-4 col-sm-4">
    <div class="well well-lg">
        <h4>
            {{-- <a href="{{ route('posts.show', $post->id ) }}">
            <a href="{{ route('posts.show', $post ) }}"> --}}
                <a href="{{ $post->path() }}">
                    {{ $post->name }}
                </a>
        </h4>
        <p><b>Author: <span style="color:rgb(1, 97, 1)">{{ $post->author->name }}</span></b></p>
        <p>
            {{ $post->body }}
        </p>
    </div>
</div>